// Data for the Quiz Final ("Diagnostica el Caso") — 10 real de-identified
// clinical cases (Marta removed 2026-09-09, unusable per the user; 6 more
// added the same day from QUIZ_FINAL_6_CASOS_ADICIONALES.md — Santiago
// Rueda, Mateo Salcedo, Álvaro Restrepo, Ricardo Peña, Camila Duarte,
// Marcela Ortiz), with per-sextant findings, gingival phenotype/recession,
// occlusal trauma, furcation, descriptive radiographic findings and case
// difficulty. Consumed by insertQuizFinal.js.
//
// The 6 added cases were translated from the source doc's English/mixed
// field names (nic_maximo/sondaje_maximo/stage_correcto/grade_correcto) to
// this file's established Spanish terminology, and their prose (which used
// bare "Stage"/"Grade" and ALL-CAPS emphasis) was rewritten to match the
// house style of the first 5 cases. `dificultad_caso` values were trimmed
// to short labels (varchar(20)) with the source's longer justification
// folded into `notas_diagnostico`, same fix as done for the original 5.
// Image URLs are all null — the source doc left every one as "pendiente".
//
// Field names translated to match this course's established terminology
// (cal not nic, pps not sondaje, estadio/grado not stage/grade) — including
// inside the nested `datos_sextantes` objects.
//
// Daniel's clinical numbers were rewritten from the source material's
// original CAL 1.5mm / normal-radiograph picture (which is Estadio I by
// definition) to support the user's explicit, twice-repeated instruction
// that Daniel must be Estadio III — see project-context.md for the exact
// values invented and why. Everyone else's numbers are as supplied.
//
// `rbl_estimado` (2026-09-09): the user supplied one whole-mouth RBL % per
// case (Daniel 15, Carmen 30, Clara 50, Yoselin 5). Where that headline
// number sits below a stated per-sextant/localized figure already in the
// case (Daniel's 35-40% in molars, Carmen's >33% "severe" description),
// kept both — the localized figure explains the focal destruction driving
// the Estadio, the new number is the whole-mouth average. Carmen's Estadio
// IV no longer needs RBL>=33% to hold since her tooth-loss count (8) alone
// satisfies that criterion per the AAP/EFP table.

export const pacientes = [
  {
    caso_numero: 1,
    nombre: 'Daniel',
    edad: 19,
    sexo: 'Masculino',
    ocupacion: 'Estudiante',
    razon_consulta: 'Me enviaron acá porque tengo las encías inflamadas',
    antecedentes_sistemicos: 'Rinitis aguda',
    valores_comorbilidades: {
      tension_arterial: '120/80 mmHg (normal)',
      frecuencia_cardiaca: '72 lpm',
      imc: 19.03,
      estado_nutricion: 'Normopeso',
    },
    medicamentos: 'No refiere',
    habitos: 'Dieta equilibrada, actividad física regular',
    antecedentes_quirurgicos: 'Ninguno',
    alergias: 'No refiere',
    hallazgos_principales:
      'Sangrado espontáneo al cepillarse. Sangrado al sondaje generalizado (100%). Edema y eritema gingival marcado. Margen gingival hipertrófico y festoneado. Defectos angulares palpables en primeros molares.',
    cal_maximo: 5.5,
    bop_porcentaje: 100,
    pps_maximo: 7,
    rbl_estimado: '15% general (35-40% en molares)',
    movilidad: 'Grado I incipiente en primeros molares (#16, #26, #36, #46)',
    dientes_presentes: 32,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 1.8,
        bop: 100,
        pps_maximo: 6,
        hallazgos: 'Máximo sangrado gingival, pero sin destrucción de soporte — inflamación pura. Dientes 11, 12 con hipertrofia marcada.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 5.5,
        bop: 95,
        pps_maximo: 7,
        hallazgos: 'Zona crítica. Defecto angular mesial y distal en #16. Furcación Grado I incipiente. Sangrado severo.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 5.0,
        bop: 90,
        pps_maximo: 6.5,
        hallazgos: 'Defecto angular en #36. Furcación Grado I incipiente. Patrón compatible con periodontitis de inicio temprano localizada a primeros molares.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 1.5,
        bop: 95,
        pps_maximo: 5,
        hallazgos: 'Sangrado severo, margen inflamado, sin pérdida de soporte real.',
      },
    },
    fenotipo_gingival: 'Grueso, redondeado',
    recesion_gingival: { presente: false, zonas: 'N/A' },
    trauma_oclusal_primario: 'No presente',
    trauma_oclusal_secundario: 'No presente',
    furcacion_presente: true,
    furcacion_detalle: 'Grado I incipiente en #16 y #36, asociada a defectos angulares mesiales/distales',
    hallazgos_radiograficos:
      'Defectos angulares verticales en mesial y distal de primeros molares (#16, #26, #36, #46), con pérdida ósea hasta el tercio medio radicular (RBL 35-40%). Resto de la dentición con cresta ósea conservada (RBL <15%). Ligamento periodontal ensanchado en los molares afectados. Patrón compatible con periodontitis de inicio temprano localizada a primeros molares.',
    patron_perdida_osea: 'Vertical/angular localizada a primeros molares; horizontal leve en el resto',
    ligamento_periodontal_estado: 'Ensanchado en primeros molares (defectos angulares); normal en el resto',
    otros_hallazgos: {
      sextante_mas_afectado: 'Sextante II (posterosuperior) y III (posteroinferior) — primeros molares',
      tipo_periodontitis: 'Periodontitis Estadio III localizada (patrón de primeros molares) — clásicamente descrita como "inicio temprano/agresiva localizada"',
      respuesta_inflamatoria: 'Exagerada para la edad, con destrucción real concomitante, no solo inflamación gingival',
    },
    periodontograma_url: '/Daniel/periodontograma_daniel.jpeg',
    radiografia_panoramica_url: '/Daniel/radiografia_daniel.jpeg',
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'C',
    notas_diagnostico:
      'Estadio III: CAL máximo 5.5mm + RBL 35-40% (tercio medio) en primeros molares, con defectos angulares y furcación incipiente — destrucción real y significativa, no solo inflamación. Localizado (afecta específicamente primeros molares, patrón clásico de periodontitis de inicio temprano). Grado C: un paciente de 19 años con esta magnitud de destrucción ya establecida implica progresión muy rápida — la discordancia edad/severidad es, por definición, un criterio de Grado C. El BOP 100% confirma actividad inflamatoria activa consistente con progresión en curso. Desafío del caso: no subestimar el Estadio solo porque el paciente es joven y la inflamación gingival domina el cuadro visible — ya existe destrucción real y localizada en primeros molares, y esa discordancia edad/severidad es precisamente lo que define el Grado C.',
    dificultad_caso: 'Alta',
  },
  {
    caso_numero: 3,
    nombre: 'Carmen',
    edad: 70,
    sexo: 'Femenino',
    ocupacion: 'Ama de casa',
    razon_consulta: 'Quiero arreglarme los dientes y tenerlos bonitos',
    antecedentes_sistemicos:
      'Dislipidemia (15 años), hipertensión arterial (20 años), apnea del sueño (CPAP nocturno), hipotiroidismo (diagnosticado en 1995)',
    valores_comorbilidades: {
      tension_arterial: '145/92 mmHg (ligeramente elevada)',
      frecuencia_cardiaca: '76 lpm',
      imc: 28.5,
      estado_nutricion: 'Sobrepeso',
      colesterol_total: '220 mg/dL (elevado)',
      tsh: '2.5 mIU/L (controlado)',
    },
    medicamentos: 'Amlodipino 5mg/día, atorvastatina 20mg/día, levotiroxina 75mcg/día',
    habitos: 'Respiración oral nocturna (por apnea). Dieta variable. Higiene oral deficiente (1x/día, sin hilo dental).',
    antecedentes_quirurgicos: 'Histerectomía (1998). Varios procedimientos odontológicos previos entre 1990 y 2000.',
    alergias: 'No refiere',
    hallazgos_principales:
      'Edema gingival generalizado severo. Eritema. Biopelícula calcificada masiva subgingival y coronal en todos los sextantes. Sangrado espontáneo al mínimo estímulo. Múltiples dientes ausentes (pérdida acumulativa). Alto acúmulo de biopelícula en prótesis parcial fija superior anterior (#11-22). Halitosis severa. Relación corona-raíz comprometida en múltiples molares.',
    cal_maximo: 6.4,
    bop_porcentaje: 47,
    pps_maximo: 6,
    rbl_estimado: '30% general (severa, defectos verticales)',
    movilidad: 'Diente 33 Grado II, diente 32 Grado I, dientes 44-45 presentes pero comprometidos',
    dientes_presentes: 24,
    dientes_ausentes: 8,
    dientes_ausentes_lista: '18, 17, 27, 28 (superiores), 37, 38, 47, 48 (inferiores)',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 5.2,
        bop: 50,
        pps_maximo: 5,
        hallazgos: 'Prótesis parcial fija #11-22. Acúmulo de biopelícula severo. Dientes 21-22 móviles Grado I.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 0,
        bop: 0,
        pps_maximo: 0,
        hallazgos: 'Edéntulo (18, 17, 27, 28 ausentes). Hueso residual bajo.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 6.4,
        bop: 60,
        pps_maximo: 6,
        hallazgos: 'Zona más afectada. Pérdida severa en 37, 38. Edema masivo. Bolsas activas.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 6.0,
        bop: 40,
        pps_maximo: 5,
        hallazgos: 'Dientes 33, 32 móviles. CAL profunda. RBL significativa.',
      },
    },
    fenotipo_gingival: 'Grueso, redondeado (edematoso)',
    recesion_gingival: { presente: true, zonas: 'Generalizada mínima (encía edematosa enmascarando potencial recesión)' },
    trauma_oclusal_primario: 'Presente — múltiples dientes superiores sin antagonistas',
    trauma_oclusal_secundario: 'Presente — movilidad en dientes 21, 22, 32, 33',
    furcacion_presente: true,
    furcacion_detalle: 'Grado 2-3 en molares remanentes, muy comprometidos',
    hallazgos_radiograficos:
      'RBL horizontal severa (~30% general) en todos los sextantes. Pérdida ósea generalizada. Defectos verticales en zonas posteriores inferiores. Ligamento periodontal ensanchado en dientes móviles (32, 33). Relación corona-raíz severamente comprometida (~0.5:1 en molares). Densidad ósea baja (compatible con edad y comorbilidades). Cálculo subgingival generalizado visible radiográficamente.',
    patron_perdida_osea: 'Horizontal severa (~30%) + defectos verticales en zonas posteriores inferiores',
    ligamento_periodontal_estado: 'Ensanchado generalizado 2-3mm por trauma, especialmente en 32 y 33',
    otros_hallazgos: {
      factores_sistemicos: 'Hipertensión, dislipidemia, respiración oral (apnea)',
      duracion_estimada: 'Progresión crónica de 20-30 años (severidad actual compatible con la pérdida de 8 dientes)',
      higiene_oral: 'Deficiente (1x/día, sin dispositivos complementarios)',
      pronostico_sin_intervencion: 'Muy pobre; pérdida dentaria progresiva prácticamente inevitable',
    },
    periodontograma_url: '/Carmen/Periodontograma_carmen.jpeg',
    radiografia_panoramica_url: '/Carmen/carmen-radiografia.png',
    radiografia_sextante_1_vestibular: '/Carmen/radiografia2_carmen.jpeg',
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 4,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio IV: CAL 6.4mm + RBL 30% general (por debajo del ≥33% de la tabla oficial por sí solo, pero la pérdida de 8 dientes atribuible a periodontitis ya define Estadio IV independientemente del RBL) + defectos verticales + movilidad Grado II + furcación severa + amenaza a la dentición completa. Localizado (la pérdida se concentra en zonas posteriores, no es uniforme). Grado B: edad 70 + comorbilidades sistémicas múltiples (hipertensión, dislipidemia, apnea) + respiración oral nocturna son modificadores significativos, pero sin tabaquismo — Grado B, no C. Pronóstico pobre sin intervención urgente. Desafío del caso: reconocer Estadio IV por la furcación + movilidad + defectos verticales; no confundir "generalizada" porque la pérdida está concentrada en sitios posteriores; reconocer las comorbilidades como modificadores de Grado sin llegar a Grado C (no fuma).',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 4,
    nombre: 'Clara',
    edad: 62,
    sexo: 'Femenino',
    ocupacion: 'Ama de casa',
    razon_consulta:
      'Valoración. Colocación de implantes 45-46 hace un año. Desea rehabilitación y manejo periodontal.',
    antecedentes_sistemicos: 'Hipotiroidismo (15 años), hipertensión arterial (10 años), reflujo gastroesofágico crónico',
    valores_comorbilidades: {
      tension_arterial: '138/88 mmHg (controlada)',
      frecuencia_cardiaca: '70 lpm',
      imc: 25.3,
      estado_nutricion: 'Normopeso',
      tsh: '1.8 mIU/L (controlado)',
      xerostomia_grado: 'Moderada (por medicamentos y comorbilidad)',
    },
    medicamentos: 'Hidrocodona 10mg (episódico, dolor), valsartán 160mg, levotiroxina 100mcg, lansoprazol 30mg',
    habitos: 'Xerostomía severa. Higiene oral con buena técnica (2x/día) pero limitada por sequedad. Respiración mixta.',
    antecedentes_quirurgicos:
      'Artroscopia bilateral de ATM (1998), tiroidectomía subtotal (2008), cirugía plástica (1995), túnel carpiano bilateral (2010), discectomía L4-L5 (2015), histerectomía (1999). Exodoncia #45-46 por periodontitis severa (2022 aprox). Colocación de implantes 45-46 (2023).',
    alergias: 'Penicilina (importante)',
    hallazgos_principales:
      'Sangrado gingival selectivo al usar hilo dental en zonas posteriores. Xerostomía evidente. Crepitación bilateral de ATM. Dolor muscular masticatorio bilateral. Respiración mixta. Halitosis leve. Edema selectivo distal en 37-38. Implantes 45-46 sin signos visibles de inflamación periimplantar.',
    cal_maximo: 5.4,
    bop_porcentaje: 18,
    pps_maximo: 5,
    rbl_estimado: '50% general, distribuida',
    movilidad: 'Presente en dientes posteriores (Grado I)',
    dientes_presentes: 28,
    dientes_ausentes: 4,
    dientes_ausentes_lista: '#45-46 (reemplazados por implantes) + 2 dientes adicionales de causa no periodontal documentada',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 3.2,
        bop: 10,
        pps_maximo: 4,
        hallazgos: 'Trauma oclusal primario en dientes 21, 23, 13. Sin sangrado espontáneo.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 4.5,
        bop: 20,
        pps_maximo: 4,
        hallazgos: 'RBL extensa (~50%). Diente 16 con trauma oclusal secundario (movilidad Grado I).',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 5.4,
        bop: 25,
        pps_maximo: 5,
        hallazgos: 'Implantes 45-46 sin periimplantitis (sondaje periimplantar normal, sin inflamación). Edema distal en 37-38. Recesión RT2-3.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 4.8,
        bop: 15,
        pps_maximo: 4,
        hallazgos: 'Trauma oclusal secundario en dientes 31, 32, 33, 41, 42, 47. Movilidad Grado I generalizada en anteriores y posteriores.',
      },
    },
    fenotipo_gingival: 'Delgado, festoneado',
    recesion_gingival: {
      presente: true,
      zonas: 'RT2 y RT3 generalizada: 16, 15, 12, 27, 24, 33, 47, 41. Severa en 37-38 (RT3).',
    },
    trauma_oclusal_primario: 'Presente — dientes 13, 23, 21 sin antagonistas suficientes',
    trauma_oclusal_secundario: 'Presente y extenso — dientes 16, 15, 12, 27, 24, 33, 47, 41 con movilidad Grado I',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL 50% general, horizontal. Múltiples defectos verticales, no profundos. Recesión gingival observable radiográficamente. Implantes 45-46 con cresta ósea circundante normal (~2-3mm). Ligamento periodontal ensanchado en múltiples dientes (trauma oclusal secundario). Relación corona-raíz comprometida en molares (~1:1). Densidad ósea normal para la edad. Sin lesiones apicales.',
    patron_perdida_osea: 'Horizontal extensa (50%), distribuida, + defectos verticales pequeños',
    ligamento_periodontal_estado: 'Ensanchado 2-3mm, generalizado en molares y posteriores, por trauma oclusal crónico',
    otros_hallazgos: {
      factor_atm: 'Disfunción de ATM bilateral con crepitación y probable desplazamiento discal',
      factor_xerostomia: 'Moderada, por lansoprazol y comorbilidad — aumenta el riesgo de caries y dificulta el control de biofilm',
      factor_implantes: 'Sin periimplantitis detectada, buena oseointegración, sin encía queratinizada (riesgo futuro)',
      duracion_estimada: 'Progresión crónica de 15-20 años. La exodoncia de 45-46 fue por periodontitis severa, no por trauma.',
      nota_alergia: 'Alergia a penicilina crítica — usar antimicrobianos alternativos si son necesarios',
    },
    periodontograma_url: '/Clara/periodontograma_clara.png',
    radiografia_panoramica_url: '/Clara/clara-radiografia.png',
    radiografia_sextante_1_vestibular: '/Clara/radiografia2_clara.jpeg',
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio III: CAL 5.4mm + RBL 50% general + defectos verticales pequeños + recesión generalizada + 4 dientes ausentes (2 por implantes, 2 de causa no periodontal documentada) + movilidad Grado I extensa (por trauma, no por periodontitis primaria) + implantes 45-46 estables sin periimplantitis. Localizado (concentrado en zonas posteriores, no uniforme). Grado B: edad 62 + xerostomía moderada + comorbilidades múltiples (hipertensión, reflujo, disfunción de ATM) + sin tabaco = Grado B. La movilidad extensa es por trauma oclusal secundario a la disfunción de ATM, no por periodontitis primaria severa; los implantes son un factor de complejidad añadido, pero están estables. Desafío del caso: reconocer Estadio III (no IV) por la ausencia de furcación y por defectos pequeños; separar el trauma oclusal de la periodontitis primaria; recordar la alergia a penicilina.',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 5,
    nombre: 'Yoselin',
    edad: 26,
    sexo: 'Femenino',
    ocupacion: 'Estudiante',
    razon_consulta: 'Tengo recesiones en anteriores inferiores',
    antecedentes_sistemicos:
      'Asma controlada desde la infancia (último episodio en 2006, hace 18 años). Dolor de rodilla derecha (causa indeterminada, pendiente valoración por especialista).',
    valores_comorbilidades: {
      tension_arterial: '110/70 mmHg (normal)',
      frecuencia_cardiaca: '62 lpm (normal)',
      imc: 19.8,
      estado_nutricion: 'Normopeso',
      control_asma: 'Excelente (sin medicamentos activos)',
    },
    medicamentos: 'Diclofenaco potásico 50mg (episódico, por dolor de rodilla). Sin medicamentos respiratorios actuales.',
    habitos:
      'Cepillado 2x/día con técnica horizontal + barrido vertical. Uso inconsistente de hilo dental (1-2x/semana). Enjuague bucal sí. Bruxismo presente (rechina de noche, sin protector). Respiración oral presente (principalmente de noche).',
    antecedentes_quirurgicos: 'Apendicectomía por apendicitis aguda (2015). Quiste ovárico izquierdo (manejo conservador).',
    alergias: 'Canela (alergia alimentaria, no relevante odontológicamente)',
    hallazgos_principales:
      'Recesiones gingivales localizadas anteroinferior (lingual): dientes 46, 42, 41, 32. Edema y eritema gingival selectivo (no generalizado) en zona anterior inferior. Sangrado gingival solo con el sondaje en zonas de recesión. Color gingival rosa pálido (no eritema generalizado). Textura punteada presente. Margen festoneado en filo de cuchillo. Papila Clase I.',
    cal_maximo: 4.4,
    bop_porcentaje: 19,
    pps_maximo: 5,
    rbl_estimado: '5% general, horizontal (leve, sin RBL severa)',
    movilidad: 'No reportada — dientes firmes',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 1.5,
        bop: 5,
        pps_maximo: 3,
        hallazgos: 'Normal. Sin sangrado. Encía rosa, firme.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 2.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Normal. Sangrado mínimo. Encía normal.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 2.5,
        bop: 15,
        pps_maximo: 3,
        hallazgos: 'Normal. Sangrado selectivo. Encía rosa.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 4.4,
        bop: 40,
        pps_maximo: 5,
        hallazgos: 'Zona crítica. Recesión generalizada en 46, 42, 41, 32. Edema selectivo. Sangrado con el sondaje. Trauma oclusal presente.',
      },
    },
    fenotipo_gingival: 'Delgado, festoneado (predisposición a recesión)',
    recesion_gingival: { presente: true, zonas: 'RT3 en dientes 42, 31, 33, 34, 35 (lingual). RT2 distal en 41, 42.' },
    trauma_oclusal_primario: 'Sí — mordida profunda anterior + bruxismo + cepillado horizontal traumático',
    trauma_oclusal_secundario: 'Secundario al trauma y al bruxismo',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL leve a moderada, horizontal, en zona anteroinferior (compatible con recesión traumática + bruxismo). Ligamento periodontal normal a ligeramente ensanchado en dientes anteroinferiores. Cresta ósea con pequeño defecto angular distal a 42. Relación corona-raíz de 1:2 a 1:1.5. Densidad ósea normal. Raíces convergentes (probable factor contribuyente a la recesión).',
    patron_perdida_osea: 'Horizontal leve + pequeño defecto vertical distal a 42',
    ligamento_periodontal_estado: 'Normal en anterosuperior; ligeramente ensanchado en anteroinferior (~1.5-2mm) por bruxismo',
    otros_hallazgos: {
      hallazgo_clave: 'CAL máximo 4.4mm, pero toda la pérdida es lingual (recesión traumática), no proximal/bucal',
      causa_recesion: 'Multifactorial: fenotipo delgado, cepillado horizontal traumático, bruxismo nocturno sin protector, respiración oral nocturna, mordida profunda anterior',
      velocidad_progresion: 'Muy lenta — aproximadamente 0.19mm/año',
      indice_biopelicula: '64% en la zona lingual (higiene deficiente en el área, especialmente sin uso regular de hilo dental)',
      factor_inflamatorio: 'Mínimo — BOP solo 19%; encía relativamente sana pese a la recesión',
    },
    periodontograma_url: '/Yoselin/periodontograma_yoselin.png',
    radiografia_panoramica_url: '/Yoselin/radiografia_yoselin.jpeg',
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 1,
    extension_correcta: 'Localizada',
    grado_correcto: 'A',
    notas_diagnostico:
      'Estadio I: CAL máximo 4.4mm, pero localizado en zona anteroinferior lingual, con un patrón recesionario, no un patrón periodontal generalizado. Localizado (afecta solo la zona anteroinferior lingual). Grado A: 26 años + velocidad de progresión lenta (≈0.19mm/año) + BOP bajo (19%) + sin comorbilidades sistémicas + sin tabaco = baja velocidad de progresión esperada. El problema principal no es periodontitis severa, sino recesión traumática por bruxismo, cepillado agresivo y respiración oral. Tratamiento: corrección de la técnica de cepillado, protector nocturno para el bruxismo, posible injerto gingival a futuro. Este es el verdadero desafío diagnóstico del quiz: el caso puede parecer "severo" por las recesiones visibles, pero es Estadio I, Grado A — hay que reconocer el patrón de pérdida ósea y de CAL (lingual, no proximal) y no confundirlo con periodontitis primaria.',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 6,
    nombre: 'Santiago Rueda',
    edad: 20,
    sexo: 'Masculino',
    ocupacion: 'Estudiante (tratamiento de ortodoncia activo)',
    razon_consulta: 'Control periodontal de rutina dentro de su tratamiento de ortodoncia',
    antecedentes_sistemicos: 'No refiere',
    valores_comorbilidades: {
      tension_arterial: 'No registrada',
      frecuencia_cardiaca: 'No registrada',
      imc: 'No registrado',
      estado_nutricion: 'No registrado',
    },
    medicamentos: 'No refiere',
    habitos: 'Portador de aparatología de ortodoncia fija (brackets en ambas arcadas)',
    antecedentes_quirurgicos: 'No refiere',
    alergias: 'No refiere',
    hallazgos_principales:
      'Aparatología ortodóncica fija completa visible. Inflamación gingival leve y puntual alrededor de algunos brackets (dificultad de higiene por retención de placa alrededor de los aditamentos), con sangrado aislado al sondaje en 3-4 sitios únicamente. No hay recesión visible ni movilidad dentaria clínica.',
    cal_maximo: 2.0,
    bop_porcentaje: 20,
    pps_maximo: 4,
    rbl_estimado: 'No significativa',
    movilidad: 'Grado 0 generalizado',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 1.2,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Sangrado aislado. Inflamación puntual alrededor de brackets.',
      },
      sextante_2: {
        nombre: 'Posterosuperior derecho',
        cal_maximo: 2.0,
        bop: 25,
        pps_maximo: 4,
        hallazgos: 'Sangrado selectivo. Dificultad de higiene por brackets.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 1.5,
        bop: 15,
        pps_maximo: 3,
        hallazgos: 'Mínimo sangrado. Encía relativamente sana.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 1.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Normal. Sin sangrado.',
      },
    },
    fenotipo_gingival: 'No registrado en la fuente',
    recesion_gingival: { presente: false, zonas: 'No detectada' },
    trauma_oclusal_primario: 'No presente',
    trauma_oclusal_secundario: 'No presente',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'Cresta ósea alveolar con altura normal en todos los sextantes. Ligamento periodontal normal. Espacios interproximales preservados. Lámina dura claramente visible. Sin lesiones óseas focales. Compatible con periodonto sano.',
    patron_perdida_osea: 'Ninguno — crestas óseas normales',
    ligamento_periodontal_estado: 'Normal, ancho uniforme 1-2mm',
    otros_hallazgos: {
      tipo_periodontitis: 'Gingivitis leve inducida por biofilm — caso límite, casi sin periodontitis',
      factores_contribuyentes: 'Retención de placa alrededor de brackets; higiene oral desafiante por ortodoncia',
      indice_biofilm: '0% (placa aislada alrededor de brackets)',
      sextante_mas_afectado: 'Posterosuperior derecho (sextante 2)',
      duracion_estimada: 'Agudo, secundario al tratamiento ortodóncico',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 1,
    extension_correcta: 'Localizada',
    grado_correcto: 'A',
    notas_diagnostico:
      'Estadio I: CAL máximo 2mm, puntual, sin RBL significativa radiográficamente y sin pérdida dentaria. Localizado (sangrado disperso en 3-4 sitios puntuales, menos del 30% de los dientes). Grado A: 20 años + BOP solo 20% + biofilm prácticamente ausente + sin comorbilidades + sin tabaco = velocidad de progresión muy baja. La inflamación es secundaria a la ortodoncia y reversible. Caso introductorio ideal para enseñar la diferencia entre gingivitis puntual por ortodoncia y periodontitis verdadera.',
    dificultad_caso: 'Baja',
  },
  {
    caso_numero: 7,
    nombre: 'Mateo Salcedo',
    edad: 25,
    sexo: 'Masculino',
    ocupacion: 'Arquitecto',
    razon_consulta:
      'Valoración periodontal por hallazgo de bolsas profundas localizadas en primeros molares, en paciente joven con el resto de la dentición clínicamente sana',
    antecedentes_sistemicos: 'No refiere',
    valores_comorbilidades: {
      tension_arterial: 'No registrada',
      frecuencia_cardiaca: 'No registrada',
      imc: 'No registrado',
      estado_nutricion: 'No registrado',
    },
    medicamentos: 'No refiere',
    habitos: 'Fumador (cantidad no especificada; dado el Grado C, se estima ≥10 cigarrillos/día)',
    antecedentes_quirurgicos: 'Osteosíntesis de rodilla izquierda',
    alergias: 'No refiere',
    hallazgos_principales:
      'Patrón de destrucción focal ("en molares") con bolsas profundas y compromiso de furca en los primeros molares (16, 26, 36 y 46/47), mientras el resto de la dentición conserva sondajes superficiales (2-4mm) y placa/sangrado bajos. Sin movilidad dentaria pese a la profundidad de las bolsas — patrón clásico de periodontitis localizada a primeros molares (antes descrita como "agresiva localizada").',
    cal_maximo: 8.0,
    bop_porcentaje: 18,
    pps_maximo: 10,
    rbl_estimado: 'Focal severa en molares',
    movilidad: 'Grado 0 (no aumentada pese a la profundidad)',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 1.0,
        bop: 5,
        pps_maximo: 3,
        hallazgos: 'Normal. Sin sangrado. Encía sana.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 8.0,
        bop: 60,
        pps_maximo: 10,
        hallazgos: 'Zona crítica. Bolsas profundas en 16 y 26. Furcación Grado II. RBL severa focal.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 8.0,
        bop: 50,
        pps_maximo: 10,
        hallazgos: 'Bolsas profundas en 36, 46 y 47. Sangrado selectivo. Defectos angulares.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 2.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Normal. Encía firme.',
      },
    },
    fenotipo_gingival: 'No registrado en la fuente',
    recesion_gingival: { presente: false, zonas: 'No detectada (el edema enmascara una posible recesión)' },
    trauma_oclusal_primario: 'No presente',
    trauma_oclusal_secundario: 'No presente',
    furcacion_presente: true,
    furcacion_detalle: 'Grado II en 16 y 26, comprometida bilateralmente',
    hallazgos_radiograficos:
      'RBL severa pero focal, únicamente en primeros molares. Defectos angulares bilaterales en 16 y 26. Ligamento periodontal normal en el resto de la dentición. Cresta ósea alveolar preservada en dientes anteriores. Densidad ósea normal.',
    patron_perdida_osea: 'Horizontal severa + defectos verticales focales en molares',
    ligamento_periodontal_estado: 'Normal en el 90% de los dientes; ligeramente ensanchado en primeros molares',
    otros_hallazgos: {
      tipo_periodontitis: 'Periodontitis localizada de inicio temprano (antes "agresiva localizada")',
      patron_caracteristico: 'Molares afectados, incisivos preservados — patrón molar-incisivo',
      factores_sospechosos: 'Fumador + patrón focal + edad joven = posible predisposición genética o inmunológica',
      discordancia_biofilm_destruccion: 'Sí — BOP bajo (18%) con destrucción severa, compatible con progresión rápida (Grado C)',
      duracion_estimada: 'Progresión probable desde la adolescencia',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'C',
    notas_diagnostico:
      'Estadio III: CAL 8-10mm en primeros molares + furcación Grado II + defectos verticales. No llega a Estadio IV: sin pérdida dentaria, movilidad Grado 0, sin colapso funcional ni amenaza a la dentición completa. Localizado: solo 4 dientes afectados (menos del 30% de la dentición), el resto preservado. Grado C: paciente joven (25 años) con una magnitud de destrucción muy severa para su edad — discordancia edad/severidad — reforzada por el tabaquismo. Caso ideal para enseñar la discordancia biofilm-destrucción como indicador de progresión rápida: BOP bajo no significa enfermedad leve.',
    dificultad_caso: 'Alta',
  },
  {
    caso_numero: 8,
    nombre: 'Álvaro Restrepo',
    edad: 44,
    sexo: 'Masculino',
    ocupacion: 'Independiente',
    razon_consulta: 'Valoración periodontal integral',
    antecedentes_sistemicos:
      'Madre hipertensa. Padre diabético. Antecedente de hipoxia cerebral a los 12 años, tratada con ácido valproico 1500mg/día durante 7 años (evento resuelto, sin secuelas, sin medicación actual).',
    valores_comorbilidades: {
      tension_arterial: 'No registrada',
      frecuencia_cardiaca: 'No registrada',
      imc: 'No registrado',
      estado_nutricion: 'No registrado',
      glucemia: 'No registrada (padre diabético — factor de riesgo heredofamiliar)',
    },
    medicamentos: 'No refiere medicación actual',
    habitos: 'No refiere tabaquismo ni otros hábitos de riesgo',
    antecedentes_quirurgicos: 'Amigdalectomía a los 5 años. Hipoxia cerebral a los 12 años (resuelta).',
    alergias: 'No refiere',
    hallazgos_principales:
      'Sangrado generalizado al sondaje, más marcado en el maxilar superior. Bolsas de 4-6mm concentradas en el sector molar y premolar. En la arcada inferior los sondajes son en su mayoría superficiales, excepto el primer molar izquierdo (37) con hasta 6mm. Sin furcaciones detectadas. Sin movilidad registrada.',
    cal_maximo: 6.0,
    bop_porcentaje: 50,
    pps_maximo: 6,
    rbl_estimado: 'Horizontal moderada',
    movilidad: 'No registrada (asumida Grado 0)',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 3.0,
        bop: 30,
        pps_maximo: 4,
        hallazgos: 'Sangrado selectivo. Encía ligeramente edematosa.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 6.0,
        bop: 70,
        pps_maximo: 6,
        hallazgos: 'Zona más afectada. Bolsas profundas. Sangrado severo. RBL moderada.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 4.0,
        bop: 40,
        pps_maximo: 4,
        hallazgos: 'Moderadamente afectado. Sondajes normales excepto 37 (6mm).',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 2.0,
        bop: 20,
        pps_maximo: 3,
        hallazgos: 'Relativamente preservado.',
      },
    },
    fenotipo_gingival: 'No registrado en la fuente',
    recesion_gingival: { presente: false, zonas: 'No registrada' },
    trauma_oclusal_primario: 'No presente',
    trauma_oclusal_secundario: 'No presente',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL horizontal moderada en el sector molar superior e inferior. Ligamento periodontal normal a ligeramente ensanchado. Cresta ósea angular distal en algunos molares. Relación corona-raíz comprometida en molares (~1:1). Densidad ósea normal. Sin lesiones apicales.',
    patron_perdida_osea: 'Horizontal moderada + pequeños defectos angulares',
    ligamento_periodontal_estado: 'Normal a ligeramente ensanchado',
    otros_hallazgos: {
      zona_critica: 'Sector posterosuperior',
      factor_contribuyente: 'BOP generalizado proporcional al biofilm (sin tabaco, respuesta esperada)',
      factor_antecedente: 'Antecedente familiar de diabetes — vigilancia recomendada',
      discordancia_biofilm_destruccion: 'No — el sangrado generalizado correlaciona con un CAL localizado (proporcional)',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio III: CAL máximo 6mm + RBL horizontal moderada + pequeños defectos angulares. Sin furcación ni pérdida dentaria — no llega a Estadio IV. Localizado: destrucción concentrada en el sector posterosuperior más el 37 puntual (no supera el 30% de la dentición). Grado B: 44 años + sin tabaco + sin diabetes documentada + BOP proporcional al CAL = velocidad de progresión moderada. El antecedente familiar de diabetes amerita seguimiento. Caso útil para diferenciar BOP generalizado (inflamación/respuesta) de destrucción generalizada (periodontitis generalizada): aquí el sangrado es amplio pero el CAL es focal.',
    dificultad_caso: 'Media',
  },
  {
    caso_numero: 9,
    nombre: 'Ricardo Peña',
    edad: 54,
    sexo: 'Masculino',
    ocupacion: 'Empleado',
    razon_consulta: 'Valoración periodontal integral en paciente fumador',
    antecedentes_sistemicos: 'Madre con cáncer de mama (factor de riesgo heredofamiliar)',
    valores_comorbilidades: {
      tension_arterial: 'No registrada',
      frecuencia_cardiaca: 'No registrada',
      imc: 'No registrado',
      estado_nutricion: 'No registrado',
    },
    medicamentos: 'No refiere',
    habitos: 'Fumador, 10-15 cigarrillos/día',
    antecedentes_quirurgicos: 'No refiere',
    alergias: 'No refiere',
    hallazgos_principales:
      'Recesión gingival generalizada (márgenes retraídos 2-6mm). Bolsas profundas generalizadas hasta 9-12mm en molares superiores. Compromiso de furca en 16 y 26 (Grado II-III). Tinción extrínseca marcada, compatible con tabaquismo. Ferulización con alambre en el sector anteroinferior (manejo de movilidad). Sangrado al sondaje en el 44% de los sitios.',
    cal_maximo: 12.0,
    bop_porcentaje: 44,
    pps_maximo: 12,
    rbl_estimado: 'Severa generalizada',
    movilidad: 'No cuantificada; la ferulización presente sugiere movilidad significativa',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 8.0,
        bop: 40,
        pps_maximo: 8,
        hallazgos: 'Recesión generalizada. Bolsas moderadas a profundas.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 12.0,
        bop: 70,
        pps_maximo: 12,
        hallazgos: 'Zona más afectada. Bolsas muy profundas. RBL severa. Furcación Grado II-III en 16 y 26.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 7.0,
        bop: 40,
        pps_maximo: 7,
        hallazgos: 'Bolsas profundas. Recesión generalizada.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 6.0,
        bop: 30,
        pps_maximo: 6,
        hallazgos: 'Ferulización con alambre (movilidad). Recesión moderada.',
      },
    },
    fenotipo_gingival: 'Grueso, edematoso',
    recesion_gingival: { presente: true, zonas: 'Generalizada: márgenes retraídos 2-6mm en múltiples dientes' },
    trauma_oclusal_primario: 'Sospechado por la ferulización',
    trauma_oclusal_secundario: 'Presente — la ferulización en anteroinferior indica manejo de movilidad',
    furcacion_presente: true,
    furcacion_detalle: 'Grado II-III en 16 y 26 (molares superiores)',
    hallazgos_radiograficos:
      'RBL horizontal severa generalizada. Defectos verticales en molares. Ligamento periodontal ensanchado (trauma oclusal). Recesión gingival observable radiográficamente. Relación corona-raíz comprometida en múltiples dientes. Densidad ósea normal. Cálculo subgingival visible.',
    patron_perdida_osea: 'Horizontal severa + defectos verticales en molares',
    ligamento_periodontal_estado: 'Ensanchado 2-3mm por trauma oclusal/inflamación',
    otros_hallazgos: {
      tipo_periodontitis: 'Estadio III-IV fronterizo (zona gris)',
      factores_de_riesgo: 'Tabaquismo 10-15 cigarrillos/día (modificador directo de Grado C)',
      signos_complejos: 'Recesión + furcación + ferulización + RBL severa',
      pregunta_pedagogica:
        '¿Movilidad ≥2 + furcación III + CAL >8mm generalizado = Estadio IV? Sin movilidad exacta ni pérdida dentaria documentadas, se mantiene Estadio III según los datos disponibles — zona gris.',
      duracion_estimada: 'Progresión crónica de 20+ años',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Generalizada',
    grado_correcto: 'C',
    notas_diagnostico:
      'Estadio III: CAL ≥5mm generalizado + furcación Grado II-III + defectos verticales. No alcanza Estadio IV porque la movilidad no está cuantificada como ≥2 (solo se observa ferulización), no hay pérdida dentaria registrada ni colapso de mordida claro — zona gris entre III y IV; según la documentación disponible se mantiene en III. Generalizado: recesión y bolsas profundas en todos los sextantes (más del 30% de la dentición). Grado C: el tabaquismo de 10-15 cigarrillos/día es un modificador directo hacia Grado C, reforzando una progresión rápida esperada. Caso útil para "zonas grises" entre III y IV: el dato que definiría Estadio IV sería movilidad ≥2 documentada, colapso de mordida, o pérdida dentaria.',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 10,
    nombre: 'Camila Duarte',
    edad: 29,
    sexo: 'Femenino',
    ocupacion: 'Independiente',
    razon_consulta: 'Consulta por movilidad y compromiso estético de un incisivo central superior',
    antecedentes_sistemicos: 'Padre falleció por insuficiencia renal',
    valores_comorbilidades: {
      tension_arterial: 'No registrada',
      frecuencia_cardiaca: 'No registrada',
      imc: 'No registrado',
      estado_nutricion: 'No registrado',
    },
    medicamentos: 'No refiere',
    habitos: 'No refiere tabaquismo ni otros hábitos de riesgo',
    antecedentes_quirurgicos: '3 partos (relevante para la historia reproductiva, no directamente odontológico)',
    alergias: 'No refiere',
    hallazgos_principales:
      'Destrucción severa y focal en el sector anterosuperior: la pieza 21 muestra extrusión/desplazamiento evidente, pérdida de inserción muy profunda y compromiso estético-funcional franco. Bolsa aislada de hasta 12mm con nivel de inserción de 14mm en ese diente. El resto de la dentición conserva sondajes leves a moderados (2-4mm) sin otros hallazgos relevantes.',
    cal_maximo: 14.0,
    bop_porcentaje: 20,
    pps_maximo: 12,
    rbl_estimado: 'Focal severa, solo en el diente 21',
    movilidad: 'Clínicamente evidente en la pieza 21 (no cuantificada)',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 14.0,
        bop: 50,
        pps_maximo: 12,
        hallazgos: 'Zona crítica única. Pieza 21 severamente comprometida. CAL extrema (14mm). Extrusión visible. Resto del sector anterior normal.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 2.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Normal. Completamente preservado.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 2.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Normal.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 2.0,
        bop: 15,
        pps_maximo: 3,
        hallazgos: 'Normal.',
      },
    },
    fenotipo_gingival: 'No registrado en la fuente',
    recesion_gingival: { presente: false, zonas: 'No registrada' },
    trauma_oclusal_primario: 'Sospechado en la pieza 21 (extrusión)',
    trauma_oclusal_secundario: 'No presente en el resto de la dentición',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL severa focal, únicamente en la pieza 21 (defecto periapical o perio-endodóntico). El resto de la cresta ósea alveolar conserva altura normal. Ligamento periodontal normal salvo en la raíz de 21 (posible lesión combinada endo-perio). Densidad ósea normal. Sin otros hallazgos focales.',
    patron_perdida_osea: 'Vertical focal, periapical/perio-endodóntico, solo en 21',
    ligamento_periodontal_estado: 'Normal en el resto de la dentición; engrosado en la raíz de 21',
    otros_hallazgos: {
      tipo_periodontitis: 'Estadio IV localizado a un solo diente (muy infrecuente)',
      pregunta_critica: '¿Lesión endo-perio combinada? ¿Trauma oclusal aislado? ¿Origen traumático o infeccioso?',
      factor_pedagogico:
        'Ilustra que el Estadio se determina por la complejidad del diente más grave, no por el número de dientes afectados',
      pronostico: 'La pieza 21 muy probablemente requiere extracción; el resto de la dentición tiene excelente pronóstico',
      duracion_estimada: 'Lesión focal, crónica o aguda reciente — indeterminada sin historia clínica',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 4,
    extension_correcta: 'Localizada',
    grado_correcto: 'A',
    notas_diagnostico:
      'Estadio IV: CAL 12-14mm en la pieza 21 (extrema) + compromiso estético-funcional franco + movilidad visible + probable necesidad de rehabilitación compleja de ese diente. Aunque afecta un solo diente, su complejidad (colapso estético-funcional) lo eleva a Estadio IV — el Estadio no es "cantidad de dientes dañados" sino "complejidad del diente más grave". Localizado: menos del 30% de la dentición afectada (1 de 28). Grado A: 29 años + sin tabaco + sin comorbilidades sistémicas + resto de la dentición sana = sin modificadores hacia Grado B o C. Caso clave para distinguir Estadio (gravedad) de Extensión (distribución).',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 11,
    nombre: 'Marcela Ortiz',
    edad: 48,
    sexo: 'Femenino',
    ocupacion: 'Secretaria',
    razon_consulta: 'No registrada en la fuente; cuadro clínico compatible con periodontitis avanzada de larga evolución',
    antecedentes_sistemicos: 'No incluidos en el material fuente',
    valores_comorbilidades: {
      tension_arterial: 'No registrada',
      frecuencia_cardiaca: 'No registrada',
      imc: 'No registrado',
      estado_nutricion: 'No registrado',
      diabetes: 'No registrada',
    },
    medicamentos: 'No registrados',
    habitos: 'No registrados',
    antecedentes_quirurgicos: 'No registrados',
    alergias: 'No registrados',
    hallazgos_principales:
      'Enfermedad periodontal avanzada y generalizada: ausencia de 3 piezas dentarias (14, 17, 24), movilidad Grado 2-3 generalizada (notoria en 18 y 21), compromiso de furca múltiple (16, 26, 27), placa visible en el 100% de las superficies, sangrado al sondaje en el 74% de los sitios. Bolsas hasta 8mm. Recesión gingival generalizada. Tinción extrínseca marcada. Pérdida de papilas interdentarias.',
    cal_maximo: 9.0,
    bop_porcentaje: 74,
    pps_maximo: 8,
    rbl_estimado: '>40% (severa generalizada)',
    movilidad: 'Grado 2-3 generalizada (notable en 18 y 21)',
    dientes_presentes: 25,
    dientes_ausentes: 3,
    dientes_ausentes_lista: '14 (superior derecho); 17 y 24 (superior izquierdo)',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 7.0,
        bop: 70,
        pps_maximo: 7,
        hallazgos: 'Ausencia de 24. Movilidad en 21-23. Recesión generalizada. Sangrado severo.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 9.0,
        bop: 85,
        pps_maximo: 8,
        hallazgos: 'Zona más afectada. Ausencia de 14 y 17. Movilidad en 18. Furcación Grado II-III en 16, 26 y 27. Bolsas profundas.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 8.0,
        bop: 70,
        pps_maximo: 7,
        hallazgos: 'Bolsas profundas. Movilidad en 36 y 37. Posible furcación. Sangrado severo.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 6.0,
        bop: 60,
        pps_maximo: 6,
        hallazgos: 'Movilidad generalizada. Recesión. Sangrado.',
      },
    },
    fenotipo_gingival: 'Grueso, edematoso, redondeado',
    recesion_gingival: { presente: true, zonas: 'Generalizada: márgenes retraídos 2-4mm en múltiples dientes' },
    trauma_oclusal_primario: 'Sospechado (ausencia de 14, 17 y 24, sin antagonistas)',
    trauma_oclusal_secundario: 'Presente — la movilidad Grado 2-3 indica trauma secundario crónico',
    furcacion_presente: true,
    furcacion_detalle: 'Grado II-III en 16, 26 y 27 (múltiple, severa)',
    hallazgos_radiograficos:
      'RBL horizontal severa generalizada (>40%). Defectos verticales en molares. Ligamento periodontal ensanchado 2-3mm generalizado (trauma oclusal). Relación corona-raíz comprometida en múltiples dientes (~0.5:1 en molares). Densidad ósea baja. Cálculo subgingival visible generalizado. Posibles lesiones apicales (requieren evaluación).',
    patron_perdida_osea: 'Horizontal severa generalizada + defectos verticales múltiples',
    ligamento_periodontal_estado: 'Ensanchado 2-3mm generalizado, por trauma e inflamación',
    otros_hallazgos: {
      tipo_periodontitis: 'Estadio IV generalizada, severa',
      factores_sistemicos_presumibles: 'No documentados en la fuente; posible diabetes mal controlada, hipertensión, o ambas',
      higiene_oral: 'Deficiente — placa 100%, sin uso aparente de hilo dental',
      duracion_estimada: 'Progresión crónica de 20-30 años (pérdida de 3 dientes + movilidad generalizada)',
      pronostico_sin_tratamiento: 'Muy pobre; pérdida dentaria progresiva casi segura',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 4,
    extension_correcta: 'Generalizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio IV: CAL ≥5mm generalizado + pérdida de 3 dientes + movilidad Grado 2-3 + furcación múltiple Grado II-III + colapso de mordida por las ausencias + trauma oclusal secundario visible — cumple todos los criterios de Estadio IV (necesidad de rehabilitación compleja). Generalizado: afectación mayor al 30% de la dentición. Grado B: sin tabaquismo ni diabetes documentados en la fuente; se asigna Grado B por evidencia de progresión severa para la edad (48 años) sin alcanzar el extremo de Grado C — de confirmarse tabaquismo o diabetes no documentados, el grado podría subir a C. Caso de cierre útil para repasar todos los criterios de Estadio IV a la vez.',
    dificultad_caso: 'Muy alta',
  },
];
