// Data for the Quiz Final ("Diagnostica el Caso") — 5 real de-identified
// clinical cases. Consumed by insertQuizFinal.js.
//
// Image URLs (periodontograma, radiografías) are intentionally left null —
// the source material marked these "PENDIENTE, usuario proporciona URL".
// Update directly in Supabase once the images are uploaded to Storage; the
// UI already renders a placeholder for any null URL.

export const pacientes = [
  {
    caso_numero: 1,
    nombre: 'Daniel',
    edad: 19,
    sexo: 'Masculino',
    ocupacion: 'Estudiante',
    razon_consulta: 'Me enviaron a acá porque tengo las encías inflamadas',
    antecedentes_sistemicos: 'Rinitis aguda',
    medicamentos: 'No refiere',
    habitos: 'Dieta equilibrada, IMC 19.03 (normopeso)',
    antecedentes_quirurgicos: 'Ninguno',
    alergias: 'No refiere',
    hallazgos_principales:
      'Todos los dientes presentes. Sangrado al sondaje generalizado. Edema y eritema gingival. Margen gingival hipertrófico.',
    cal_maximo: 1.5,
    bop_porcentaje: 100,
    pps_maximo: 6,
    rbl_estimado: 'No significativa',
    movilidad: 'Grados I-II en dientes anteriores',
    dientes_presentes: 32,
    dientes_ausentes: 0,
    otros_hallazgos: {
      ligamento_periodontal: 'Normal',
      patron_perdida_osea: 'Ninguno',
      sextante_mas_afectado: 'Sextante II (anterosuperior)',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 1,
    extension_correcta: 'Localizada',
    grado_correcto: 'C',
    notas_diagnostico:
      'Estadio I: CAL 1.5mm (perímetro normal). Localizado (afecta zona anterior superior). Grado C: edad joven + BOP 100% + sangrado generalizado sugiere progresión rápida sin control.',
  },
  {
    caso_numero: 2,
    nombre: 'Marta',
    edad: 36,
    sexo: 'Femenino',
    ocupacion: 'Niñera',
    razon_consulta: 'Vengo a que revisen mi implante',
    antecedentes_sistemicos: 'Ninguno relevante',
    medicamentos: 'No refiere',
    habitos: 'Dieta equilibrada, IMC 23.1 (normopeso)',
    antecedentes_quirurgicos: 'Quiste ovárico izquierdo (2015), Pomeroy (2016), exodoncia #36 por caries',
    alergias: 'No refiere',
    hallazgos_principales:
      'Diente #36 ausente (exodoncia por caries). Sangrado selectivo al sondaje. Sin edema generalizado. Recesión gingival moderada en sector posterior.',
    cal_maximo: 6.4,
    bop_porcentaje: 25,
    pps_maximo: 7,
    rbl_estimado: '15-25% (tercio coronal)',
    movilidad: 'Presente en diente 18',
    dientes_presentes: 31,
    dientes_ausentes: 1,
    otros_hallazgos: {
      patron_perdida_osea: 'Horizontal moderada',
      relacion_corona_raiz: 'Comprometida en molares inferiores',
      sextante_critico: 'Sextante posterior inferior izquierdo',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: '/quiz-marta-radiografia-panoramica.png',
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 2,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio II: CAL 3-4mm + RBL 15-25% tercio coronal + 1 diente ausente (caries, no periodontitis). Localizado (afecta sector posterior). Grado B: sin comorbilidades, sin tabaco, cumplimiento probable.',
  },
  {
    caso_numero: 3,
    nombre: 'Carmen',
    edad: 70,
    sexo: 'Femenino',
    ocupacion: 'Ama de casa',
    razon_consulta: 'Quiero arreglarme los dientes y tenerlos bonitos',
    antecedentes_sistemicos: 'Dislipidemia, hipertensión, apnea del sueño, hipotiroidismo',
    medicamentos: 'Amlodipino, atorvastatina, levotiroxina',
    habitos: 'Respiración mixta',
    antecedentes_quirurgicos: 'Múltiples (ver historia clínica detallada)',
    alergias: 'No refiere',
    hallazgos_principales:
      'Edema gingival generalizado. Eritema. Biopelícula calcificada subgingival y coronal generalizada. Múltiples dientes ausentes. Alto acúmulo de biopelícula en prótesis parcial fija superior anterior.',
    cal_maximo: 6.4,
    bop_porcentaje: 47,
    pps_maximo: 6,
    rbl_estimado: '>33% (horizontal moderada a severa)',
    movilidad: 'Diente 33 Grado II, diente 32 Grado I',
    dientes_presentes: 24,
    dientes_ausentes: 8,
    otros_hallazgos: {
      patron_perdida_osea: 'Horizontal severa',
      ligamento_periodontal: 'Ensanchado',
      relacion_corona_raiz: 'Comprometida',
      recesion_gingival: 'Presente',
      trauma_oclusal: 'Presente en varios dientes',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 4,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio IV: CAL 6.4mm + RBL >33% + pérdida de 8 dientes + movilidad Grado II + múltiples comorbilidades que requieren manejo complejo. Localizado (concentrado en zonas específicas). Grado B: edad avanzada + comorbilidades sistémicas modifican la velocidad de progresión, sin evidencia de aceleración.',
  },
  {
    caso_numero: 4,
    nombre: 'Clara',
    edad: 62,
    sexo: 'Femenino',
    ocupacion: 'Ama de casa',
    razon_consulta:
      'Valoración. Colocación de implantes 45-46 hace un año. Desea rehabilitación y manejo periodontal.',
    antecedentes_sistemicos: 'Hipotiroidismo, hipertensión arterial, reflujo gástrico',
    medicamentos: 'Hidrocodona 10mg, valsartán 160mg, levotiroxina 100mg, lansoprazol 30mg',
    habitos: 'Xerostomía',
    antecedentes_quirurgicos:
      'Artroscopia de ATM, osteosíntesis rotuliana, tiroidectomía, cirugía plástica, túnel carpiano, ureteroscopia, discectomía L4-L5, histerectomía',
    alergias: 'Penicilina',
    hallazgos_principales:
      'Sangrado gingival al usar hilo dental. Xerostomía. Crepitación bilateral de ATM. Dolor muscular masticatorio. Respiración mixta. Halitosis. Edema selectivo. Implantes 45-46 sin encía queratinizada.',
    cal_maximo: 5.4,
    bop_porcentaje: 18,
    pps_maximo: 5,
    rbl_estimado: 'Leve a moderada (múltiples dientes)',
    movilidad: 'Presente en dientes posteriores',
    dientes_presentes: 28,
    dientes_ausentes: 4,
    otros_hallazgos: {
      patron_perdida_osea: 'Horizontal moderada a severa',
      ligamento_periodontal: 'Ensanchado en puntos específicos',
      relacion_corona_raiz: 'Comprometida en molares',
      recesion_gingival: 'RT2 y RT3 generalizada',
      trauma_oclusal_primario: 'Dientes 13, 23, 21',
      trauma_oclusal_secundario: 'Dientes 16, 15, 12, 27, 24, 33, 47, 41',
      fenotipo_gingival: 'Delgado festoneado',
      implantes: 'Posición 45-46, sin periimplantitis, sin encía queratinizada alrededor',
      condiciones_atm: 'Desplazamiento discal, crepitación',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio III: CAL 5.4mm + RBL leve-moderada + defectos verticales + recesión generalizada + 4 dientes ausentes + trauma oclusal secundario + implantes sin periimplantitis. Localizado (concentrado en zonas posteriores). Grado B: edad 62 + xerostomía + comorbilidades sistémicas complejas + implantes estables requieren manejo cuidadoso, pero sin indicación de progresión rápida.',
  },
  {
    caso_numero: 5,
    nombre: 'Yoselin',
    edad: 26,
    sexo: 'Femenino',
    ocupacion: 'Estudiante',
    razon_consulta: 'Tengo recesiones en anteriores inferiores',
    antecedentes_sistemicos:
      'Asma controlada (diagnosticada en la infancia, controlada con salbutamol + budesonide, último episodio en 2006). Dolor de rodilla derecha (pendiente valoración por especialista).',
    medicamentos: 'Diclofenaco potásico 50mg (episódico, por dolor de rodilla)',
    habitos:
      'Higiene oral 2x/día (técnica horizontal y de barrido), uso ocasional de hilo dental, enjuague sí, bruxismo presente, respiración oral presente, IMC 19.8 (normopeso)',
    antecedentes_quirurgicos: 'Apendicectomía (2015), quiste ovárico izquierdo',
    alergias: 'Canela',
    hallazgos_principales:
      'Recesiones gingivales en anteriores inferiores (lingual: 46, 42, 41, 32). Edema y eritema gingival selectivo. Sangrado gingival. Color rosa pálido. Textura punteada. Margen festoneado en filo de cuchillo. Papila Clase I.',
    cal_maximo: 4.4,
    bop_porcentaje: 19,
    pps_maximo: 5,
    rbl_estimado: 'Leve a moderada (horizontal)',
    movilidad: 'No reportada',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    otros_hallazgos: {
      patron_perdida_osea: 'Horizontal leve a moderada',
      ligamento_periodontal: 'Normal a ensanchado en puntos específicos',
      relacion_corona_raiz: '1:2 a 1:1.5',
      recesion_gingival: 'RT3 en dientes 42, 31, 33, 34, 35',
      fenotipo_gingival: 'Delgado festoneado',
      trauma_oclusal: 'Presente en anteriores inferiores',
      bruxismo: 'Sí',
      respiracion_oral: 'Sí',
      indice_biopelicula: '64% (higiene deficiente)',
      perdida_osea_por_anio: 0.19,
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 1,
    extension_correcta: 'Localizada',
    grado_correcto: 'A',
    notas_diagnostico:
      'Estadio I: CAL máximo 4.4mm, pero localizado en zona anterior; RBL leve. Localizado (recesiones + trauma oclusal anteroinferior específico). Grado A: edad joven + pérdida ósea lenta (0.19mm/año) + BOP bajo (19%) + sin comorbilidades sistémicas = baja velocidad de progresión. El problema principal es bruxismo + respiración oral + trauma oclusal, no periodontitis severa.',
  },
];
