// Data for the Quiz Final ("Diagnostica el Caso") — 5 real de-identified
// clinical cases, expanded 2026-08-22 with per-sextant findings, gingival
// phenotype/recession, occlusal trauma, furcation, descriptive radiographic
// findings and case difficulty. Consumed by insertQuizFinal.js.
//
// Field names translated to match this course's established terminology
// (cal not nic, pps not sondaje, estadio/grado not stage/grade) — including
// inside the nested `datos_sextantes` objects.
//
// Daniel's clinical numbers were rewritten from the source material's
// original CAL 1.5mm / normal-radiograph picture (which is Estadio I by
// definition) to support the user's explicit, twice-repeated instruction
// that Daniel must be Estadio III — see project-context.md for the exact
// values invented and why. Everyone else's numbers are as supplied.
//
// Image URLs are null except Marta's panoramic radiograph (already placed
// in public/ before this expansion). Update directly in Supabase (or
// re-run the seed script after editing this file) once more images exist.

export const pacientes = [
  {
    caso_numero: 1,
    nombre: 'Daniel',
    edad: 19,
    sexo: 'Masculino',
    ocupacion: 'Estudiante',
    razon_consulta: 'Me enviaron acá porque tengo las encías inflamadas',
    antecedentes_sistemicos: 'Rinitis aguda',
    valores_comorbilidades: {
      tension_arterial: '120/80 mmHg (normal)',
      frecuencia_cardiaca: '72 lpm',
      imc: 19.03,
      estado_nutricion: 'Normopeso',
    },
    medicamentos: 'No refiere',
    habitos: 'Dieta equilibrada, actividad física regular',
    antecedentes_quirurgicos: 'Ninguno',
    alergias: 'No refiere',
    hallazgos_principales:
      'Sangrado espontáneo al cepillarse. Sangrado al sondaje generalizado (100%). Edema y eritema gingival marcado. Margen gingival hipertrófico y festoneado. Defectos angulares palpables en primeros molares.',
    cal_maximo: 5.5,
    bop_porcentaje: 100,
    pps_maximo: 7,
    rbl_estimado: '35-40% en molares; <15% resto',
    movilidad: 'Grado I incipiente en primeros molares (#16, #26, #36, #46)',
    dientes_presentes: 32,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 1.8,
        bop: 100,
        pps_maximo: 6,
        hallazgos: 'Máximo sangrado gingival, pero sin destrucción de soporte — inflamación pura. Dientes 11, 12 con hipertrofia marcada.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 5.5,
        bop: 95,
        pps_maximo: 7,
        hallazgos: 'Zona crítica. Defecto angular mesial y distal en #16. Furcación Grado I incipiente. Sangrado severo.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 5.0,
        bop: 90,
        pps_maximo: 6.5,
        hallazgos: 'Defecto angular en #36. Furcación Grado I incipiente. Patrón compatible con periodontitis de inicio temprano localizada a primeros molares.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 1.5,
        bop: 95,
        pps_maximo: 5,
        hallazgos: 'Sangrado severo, margen inflamado, sin pérdida de soporte real.',
      },
    },
    fenotipo_gingival: 'Grueso, redondeado',
    recesion_gingival: { presente: false, zonas: 'N/A' },
    trauma_oclusal_primario: 'No presente',
    trauma_oclusal_secundario: 'No presente',
    furcacion_presente: true,
    furcacion_detalle: 'Grado I incipiente en #16 y #36, asociada a defectos angulares mesiales/distales',
    hallazgos_radiograficos:
      'Defectos angulares verticales en mesial y distal de primeros molares (#16, #26, #36, #46), con pérdida ósea hasta el tercio medio radicular (RBL 35-40%). Resto de la dentición con cresta ósea conservada (RBL <15%). Ligamento periodontal ensanchado en los molares afectados. Patrón compatible con periodontitis de inicio temprano localizada a primeros molares.',
    patron_perdida_osea: 'Vertical/angular localizada a primeros molares; horizontal leve en el resto',
    ligamento_periodontal_estado: 'Ensanchado en primeros molares (defectos angulares); normal en el resto',
    otros_hallazgos: {
      sextante_mas_afectado: 'Sextante II (posterosuperior) y III (posteroinferior) — primeros molares',
      tipo_periodontitis: 'Periodontitis Estadio III localizada (patrón de primeros molares) — clásicamente descrita como "inicio temprano/agresiva localizada"',
      respuesta_inflamatoria: 'Exagerada para la edad, con destrucción real concomitante, no solo inflamación gingival',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'C',
    notas_diagnostico:
      'Estadio III: CAL máximo 5.5mm + RBL 35-40% (tercio medio) en primeros molares, con defectos angulares y furcación incipiente — destrucción real y significativa, no solo inflamación. Localizado (afecta específicamente primeros molares, patrón clásico de periodontitis de inicio temprano). Grado C: un paciente de 19 años con esta magnitud de destrucción ya establecida implica progresión muy rápida — la discordancia edad/severidad es, por definición, un criterio de Grado C. El BOP 100% confirma actividad inflamatoria activa consistente con progresión en curso. Desafío del caso: no subestimar el Estadio solo porque el paciente es joven y la inflamación gingival domina el cuadro visible — ya existe destrucción real y localizada en primeros molares, y esa discordancia edad/severidad es precisamente lo que define el Grado C.',
    dificultad_caso: 'Alta',
  },
  {
    caso_numero: 2,
    nombre: 'Marta',
    edad: 36,
    sexo: 'Femenino',
    ocupacion: 'Niñera',
    razon_consulta: 'Vengo a que revisen mi implante',
    antecedentes_sistemicos:
      'Ninguno sistémico. Antecedentes obstétricos: ligadura tubaria (2016), quiste ovárico izquierdo (2015).',
    valores_comorbilidades: {
      tension_arterial: '115/75 mmHg (normal)',
      frecuencia_cardiaca: '68 lpm',
      imc: 23.1,
      estado_nutricion: 'Normopeso',
      control_glucemico: 'No diabética (glucemia en ayuno 95 mg/dL)',
    },
    medicamentos: 'Anticoncepción hormonal',
    habitos: 'Dieta equilibrada, higiene oral 1x/día (insuficiente), uso inconsistente de hilo dental',
    antecedentes_quirurgicos: 'Exodoncia #36 por caries extensa (2012)',
    alergias: 'No refiere',
    hallazgos_principales:
      'Diente #36 ausente desde 2012 (exodoncia por caries). Sangrado selectivo al sondaje en zona distal. Edema selectivo distal 37-38. Recesión gingival moderada en zona posteroinferior izquierda. Sin edema generalizado. Margen gingival festoneado en molar 37.',
    cal_maximo: 6.4,
    bop_porcentaje: 25,
    pps_maximo: 7,
    rbl_estimado: '15-25% (tercio coronal, horizontal)',
    movilidad: 'Grado I en diente 18 (molar superior derecho)',
    dientes_presentes: 31,
    dientes_ausentes: 1,
    dientes_ausentes_lista: '#36 (caries, no periodontitis)',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 2.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Sin sangrado. Encía rosa. Margen normal.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 3.5,
        bop: 30,
        pps_maximo: 5,
        hallazgos: 'Sangrado selectivo distal en 18. Movilidad Grado I en 18. RBL 20%.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 6.4,
        bop: 40,
        pps_maximo: 7,
        hallazgos: 'Zona crítica. CAL profunda en zona distal de 37-38. Recesión RT2. RBL 25% tercio coronal.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 2.2,
        bop: 15,
        pps_maximo: 3,
        hallazgos: 'Normal. Sin sangrado. Encía firme.',
      },
    },
    fenotipo_gingival: 'Medio, festoneado',
    recesion_gingival: { presente: true, zonas: 'RT2 en dientes 37-38 (lingual), RT1 distal 37' },
    trauma_oclusal_primario: 'No presente',
    trauma_oclusal_secundario: 'Presente en diente 18 (movilidad Grado I)',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL horizontal moderada en molares inferiores (15-25%). Ligamento periodontal ensanchado en diente 18 (trauma oclusal secundario). Relación corona-raíz comprometida en 37-38 (~1:1). Cresta ósea angular distal a 38. Densidad ósea normal. Sin lesiones apicales.',
    patron_perdida_osea: 'Horizontal moderada + defecto angular distal a 38',
    ligamento_periodontal_estado: 'Ensanchado en 18 (~2.5-3mm) por trauma; normal en el resto',
    otros_hallazgos: {
      zona_critica: 'Sextante posteroinferior izquierdo',
      factor_contribuyente: 'Higiene oral deficiente (1x/día) + ausencia de #36 + trauma oclusal secundario en 18',
      relacion_corona_raiz: 'Comprometida en molares inferiores',
      duracion_estimada: 'Progresión crónica de aproximadamente 10 años (desde la exodoncia en 2012)',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: '/quiz-marta-radiografia-panoramica.png',
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 2,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio II: CAL 3-4mm en zona posteroinferior + RBL 15-25% tercio coronal + defecto angular distal a 38 + 1 diente ausente (caries, no periodontitis). Localizado (concentrado en el sextante posteroinferior). Grado B: edad 36 + sin comorbilidades + sin tabaco + control glucémico normal + higiene deficiente pero mejorable = progresión moderada esperada. El trauma oclusal secundario en 18 es un factor contribuyente, no el criterio que define el Estadio. Desafío del caso: no atribuir la ausencia de #36 a periodontitis (fue caries); reconocer el defecto angular como factor de complejidad; interpretar la movilidad en 18 como trauma oclusal secundario, no como elevador primario del Estadio.',
    dificultad_caso: 'Alta',
  },
  {
    caso_numero: 3,
    nombre: 'Carmen',
    edad: 70,
    sexo: 'Femenino',
    ocupacion: 'Ama de casa',
    razon_consulta: 'Quiero arreglarme los dientes y tenerlos bonitos',
    antecedentes_sistemicos:
      'Dislipidemia (15 años), hipertensión arterial (20 años), apnea del sueño (CPAP nocturno), hipotiroidismo (diagnosticado en 1995)',
    valores_comorbilidades: {
      tension_arterial: '145/92 mmHg (ligeramente elevada)',
      frecuencia_cardiaca: '76 lpm',
      imc: 28.5,
      estado_nutricion: 'Sobrepeso',
      colesterol_total: '220 mg/dL (elevado)',
      tsh: '2.5 mIU/L (controlado)',
    },
    medicamentos: 'Amlodipino 5mg/día, atorvastatina 20mg/día, levotiroxina 75mcg/día',
    habitos: 'Respiración oral nocturna (por apnea). Dieta variable. Higiene oral deficiente (1x/día, sin hilo dental).',
    antecedentes_quirurgicos: 'Histerectomía (1998). Varios procedimientos odontológicos previos entre 1990 y 2000.',
    alergias: 'No refiere',
    hallazgos_principales:
      'Edema gingival generalizado severo. Eritema. Biopelícula calcificada masiva subgingival y coronal en todos los sextantes. Sangrado espontáneo al mínimo estímulo. Múltiples dientes ausentes (pérdida acumulativa). Alto acúmulo de biopelícula en prótesis parcial fija superior anterior (#11-22). Halitosis severa. Relación corona-raíz comprometida en múltiples molares.',
    cal_maximo: 6.4,
    bop_porcentaje: 47,
    pps_maximo: 6,
    rbl_estimado: '>33% (horizontal severa + defectos verticales)',
    movilidad: 'Diente 33 Grado II, diente 32 Grado I, dientes 44-45 presentes pero comprometidos',
    dientes_presentes: 24,
    dientes_ausentes: 8,
    dientes_ausentes_lista: '18, 17, 27, 28 (superiores), 37, 38, 47, 48 (inferiores)',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 5.2,
        bop: 50,
        pps_maximo: 5,
        hallazgos: 'Prótesis parcial fija #11-22. Acúmulo de biopelícula severo. Dientes 21-22 móviles Grado I.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 0,
        bop: 0,
        pps_maximo: 0,
        hallazgos: 'Edéntulo (18, 17, 27, 28 ausentes). Hueso residual bajo.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 6.4,
        bop: 60,
        pps_maximo: 6,
        hallazgos: 'Zona más afectada. Pérdida severa en 37, 38. Edema masivo. Bolsas activas.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 6.0,
        bop: 40,
        pps_maximo: 5,
        hallazgos: 'Dientes 33, 32 móviles. CAL profunda. RBL significativa.',
      },
    },
    fenotipo_gingival: 'Grueso, redondeado (edematoso)',
    recesion_gingival: { presente: true, zonas: 'Generalizada mínima (encía edematosa enmascarando potencial recesión)' },
    trauma_oclusal_primario: 'Presente — múltiples dientes superiores sin antagonistas',
    trauma_oclusal_secundario: 'Presente — movilidad en dientes 21, 22, 32, 33',
    furcacion_presente: true,
    furcacion_detalle: 'Grado 2-3 en molares remanentes, muy comprometidos',
    hallazgos_radiograficos:
      'RBL horizontal severa >33% en todos los sextantes. Pérdida ósea generalizada. Defectos verticales en zonas posteriores inferiores. Ligamento periodontal ensanchado en dientes móviles (32, 33). Relación corona-raíz severamente comprometida (~0.5:1 en molares). Densidad ósea baja (compatible con edad y comorbilidades). Cálculo subgingival generalizado visible radiográficamente.',
    patron_perdida_osea: 'Horizontal severa (>33%) + defectos verticales en zonas posteriores inferiores',
    ligamento_periodontal_estado: 'Ensanchado generalizado 2-3mm por trauma, especialmente en 32 y 33',
    otros_hallazgos: {
      factores_sistemicos: 'Hipertensión, dislipidemia, respiración oral (apnea)',
      duracion_estimada: 'Progresión crónica de 20-30 años (severidad actual compatible con la pérdida de 8 dientes)',
      higiene_oral: 'Deficiente (1x/día, sin dispositivos complementarios)',
      pronostico_sin_intervencion: 'Muy pobre; pérdida dentaria progresiva prácticamente inevitable',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 4,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio IV: CAL 6.4mm + RBL >33% + defectos verticales + pérdida de 8 dientes + movilidad Grado II + furcación severa + amenaza a la dentición completa. Localizado (la pérdida se concentra en zonas posteriores, no es uniforme). Grado B: edad 70 + comorbilidades sistémicas múltiples (hipertensión, dislipidemia, apnea) + respiración oral nocturna son modificadores significativos, pero sin tabaquismo — Grado B, no C. Pronóstico pobre sin intervención urgente. Desafío del caso: reconocer Estadio IV por la furcación + movilidad + defectos verticales; no confundir "generalizada" porque la pérdida está concentrada en sitios posteriores; reconocer las comorbilidades como modificadores de Grado sin llegar a Grado C (no fuma).',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 4,
    nombre: 'Clara',
    edad: 62,
    sexo: 'Femenino',
    ocupacion: 'Ama de casa',
    razon_consulta:
      'Valoración. Colocación de implantes 45-46 hace un año. Desea rehabilitación y manejo periodontal.',
    antecedentes_sistemicos: 'Hipotiroidismo (15 años), hipertensión arterial (10 años), reflujo gastroesofágico crónico',
    valores_comorbilidades: {
      tension_arterial: '138/88 mmHg (controlada)',
      frecuencia_cardiaca: '70 lpm',
      imc: 25.3,
      estado_nutricion: 'Normopeso',
      tsh: '1.8 mIU/L (controlado)',
      xerostomia_grado: 'Moderada (por medicamentos y comorbilidad)',
    },
    medicamentos: 'Hidrocodona 10mg (episódico, dolor), valsartán 160mg, levotiroxina 100mcg, lansoprazol 30mg',
    habitos: 'Xerostomía severa. Higiene oral con buena técnica (2x/día) pero limitada por sequedad. Respiración mixta.',
    antecedentes_quirurgicos:
      'Artroscopia bilateral de ATM (1998), tiroidectomía subtotal (2008), cirugía plástica (1995), túnel carpiano bilateral (2010), discectomía L4-L5 (2015), histerectomía (1999). Exodoncia #45-46 por periodontitis severa (2022 aprox). Colocación de implantes 45-46 (2023).',
    alergias: 'Penicilina (importante)',
    hallazgos_principales:
      'Sangrado gingival selectivo al usar hilo dental en zonas posteriores. Xerostomía evidente. Crepitación bilateral de ATM. Dolor muscular masticatorio bilateral. Respiración mixta. Halitosis leve. Edema selectivo distal en 37-38. Implantes 45-46 sin signos visibles de inflamación periimplantar.',
    cal_maximo: 5.4,
    bop_porcentaje: 18,
    pps_maximo: 5,
    rbl_estimado: 'Leve a moderada, distribuida',
    movilidad: 'Presente en dientes posteriores (Grado I)',
    dientes_presentes: 28,
    dientes_ausentes: 4,
    dientes_ausentes_lista: '#45-46 (reemplazados por implantes) + 2 dientes adicionales de causa no periodontal documentada',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 3.2,
        bop: 10,
        pps_maximo: 4,
        hallazgos: 'Trauma oclusal primario en dientes 21, 23, 13. Sin sangrado espontáneo.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 4.5,
        bop: 20,
        pps_maximo: 4,
        hallazgos: 'RBL leve-moderada. Diente 16 con trauma oclusal secundario (movilidad Grado I).',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 5.4,
        bop: 25,
        pps_maximo: 5,
        hallazgos: 'Implantes 45-46 sin periimplantitis (sondaje periimplantar normal, sin inflamación). Edema distal en 37-38. Recesión RT2-3.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 4.8,
        bop: 15,
        pps_maximo: 4,
        hallazgos: 'Trauma oclusal secundario en dientes 31, 32, 33, 41, 42, 47. Movilidad Grado I generalizada en anteriores y posteriores.',
      },
    },
    fenotipo_gingival: 'Delgado, festoneado',
    recesion_gingival: {
      presente: true,
      zonas: 'RT2 y RT3 generalizada: 16, 15, 12, 27, 24, 33, 47, 41. Severa en 37-38 (RT3).',
    },
    trauma_oclusal_primario: 'Presente — dientes 13, 23, 21 sin antagonistas suficientes',
    trauma_oclusal_secundario: 'Presente y extenso — dientes 16, 15, 12, 27, 24, 33, 47, 41 con movilidad Grado I',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL leve a moderada, horizontal. Múltiples defectos verticales, no profundos. Recesión gingival observable radiográficamente. Implantes 45-46 con cresta ósea circundante normal (~2-3mm). Ligamento periodontal ensanchado en múltiples dientes (trauma oclusal secundario). Relación corona-raíz comprometida en molares (~1:1). Densidad ósea normal para la edad. Sin lesiones apicales.',
    patron_perdida_osea: 'Horizontal leve a moderada, distribuida, + defectos verticales pequeños',
    ligamento_periodontal_estado: 'Ensanchado 2-3mm, generalizado en molares y posteriores, por trauma oclusal crónico',
    otros_hallazgos: {
      factor_atm: 'Disfunción de ATM bilateral con crepitación y probable desplazamiento discal',
      factor_xerostomia: 'Moderada, por lansoprazol y comorbilidad — aumenta el riesgo de caries y dificulta el control de biofilm',
      factor_implantes: 'Sin periimplantitis detectada, buena oseointegración, sin encía queratinizada (riesgo futuro)',
      duracion_estimada: 'Progresión crónica de 15-20 años. La exodoncia de 45-46 fue por periodontitis severa, no por trauma.',
      nota_alergia: 'Alergia a penicilina crítica — usar antimicrobianos alternativos si son necesarios',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 3,
    extension_correcta: 'Localizada',
    grado_correcto: 'B',
    notas_diagnostico:
      'Estadio III: CAL 5.4mm + RBL leve-moderada + defectos verticales pequeños + recesión generalizada + 4 dientes ausentes (2 por implantes, 2 de causa no periodontal documentada) + movilidad Grado I extensa (por trauma, no por periodontitis primaria) + implantes 45-46 estables sin periimplantitis. Localizado (concentrado en zonas posteriores, no uniforme). Grado B: edad 62 + xerostomía moderada + comorbilidades múltiples (hipertensión, reflujo, disfunción de ATM) + sin tabaco = Grado B. La movilidad extensa es por trauma oclusal secundario a la disfunción de ATM, no por periodontitis primaria severa; los implantes son un factor de complejidad añadido, pero están estables. Desafío del caso: reconocer Estadio III (no IV) por la ausencia de furcación y por defectos pequeños; separar el trauma oclusal de la periodontitis primaria; recordar la alergia a penicilina.',
    dificultad_caso: 'Muy alta',
  },
  {
    caso_numero: 5,
    nombre: 'Yoselin',
    edad: 26,
    sexo: 'Femenino',
    ocupacion: 'Estudiante',
    razon_consulta: 'Tengo recesiones en anteriores inferiores',
    antecedentes_sistemicos:
      'Asma controlada desde la infancia (último episodio en 2006, hace 18 años). Dolor de rodilla derecha (causa indeterminada, pendiente valoración por especialista).',
    valores_comorbilidades: {
      tension_arterial: '110/70 mmHg (normal)',
      frecuencia_cardiaca: '62 lpm (normal)',
      imc: 19.8,
      estado_nutricion: 'Normopeso',
      control_asma: 'Excelente (sin medicamentos activos)',
    },
    medicamentos: 'Diclofenaco potásico 50mg (episódico, por dolor de rodilla). Sin medicamentos respiratorios actuales.',
    habitos:
      'Cepillado 2x/día con técnica horizontal + barrido vertical. Uso inconsistente de hilo dental (1-2x/semana). Enjuague bucal sí. Bruxismo presente (rechina de noche, sin protector). Respiración oral presente (principalmente de noche).',
    antecedentes_quirurgicos: 'Apendicectomía por apendicitis aguda (2015). Quiste ovárico izquierdo (manejo conservador).',
    alergias: 'Canela (alergia alimentaria, no relevante odontológicamente)',
    hallazgos_principales:
      'Recesiones gingivales localizadas anteroinferior (lingual): dientes 46, 42, 41, 32. Edema y eritema gingival selectivo (no generalizado) en zona anterior inferior. Sangrado gingival solo con el sondaje en zonas de recesión. Color gingival rosa pálido (no eritema generalizado). Textura punteada presente. Margen festoneado en filo de cuchillo. Papila Clase I.',
    cal_maximo: 4.4,
    bop_porcentaje: 19,
    pps_maximo: 5,
    rbl_estimado: 'Leve a moderada, horizontal (sin RBL severa)',
    movilidad: 'No reportada — dientes firmes',
    dientes_presentes: 28,
    dientes_ausentes: 0,
    dientes_ausentes_lista: 'N/A',
    datos_sextantes: {
      sextante_1: {
        nombre: 'Anterosuperior',
        cal_maximo: 1.5,
        bop: 5,
        pps_maximo: 3,
        hallazgos: 'Normal. Sin sangrado. Encía rosa, firme.',
      },
      sextante_2: {
        nombre: 'Posterosuperior',
        cal_maximo: 2.0,
        bop: 10,
        pps_maximo: 3,
        hallazgos: 'Normal. Sangrado mínimo. Encía normal.',
      },
      sextante_3: {
        nombre: 'Posteroinferior',
        cal_maximo: 2.5,
        bop: 15,
        pps_maximo: 3,
        hallazgos: 'Normal. Sangrado selectivo. Encía rosa.',
      },
      sextante_4: {
        nombre: 'Anteroinferior',
        cal_maximo: 4.4,
        bop: 40,
        pps_maximo: 5,
        hallazgos: 'Zona crítica. Recesión generalizada en 46, 42, 41, 32. Edema selectivo. Sangrado con el sondaje. Trauma oclusal presente.',
      },
    },
    fenotipo_gingival: 'Delgado, festoneado (predisposición a recesión)',
    recesion_gingival: { presente: true, zonas: 'RT3 en dientes 42, 31, 33, 34, 35 (lingual). RT2 distal en 41, 42.' },
    trauma_oclusal_primario: 'Sí — mordida profunda anterior + bruxismo + cepillado horizontal traumático',
    trauma_oclusal_secundario: 'Secundario al trauma y al bruxismo',
    furcacion_presente: false,
    furcacion_detalle: 'N/A',
    hallazgos_radiograficos:
      'RBL leve a moderada, horizontal, en zona anteroinferior (compatible con recesión traumática + bruxismo). Ligamento periodontal normal a ligeramente ensanchado en dientes anteroinferiores. Cresta ósea con pequeño defecto angular distal a 42. Relación corona-raíz de 1:2 a 1:1.5. Densidad ósea normal. Raíces convergentes (probable factor contribuyente a la recesión).',
    patron_perdida_osea: 'Horizontal leve + pequeño defecto vertical distal a 42',
    ligamento_periodontal_estado: 'Normal en anterosuperior; ligeramente ensanchado en anteroinferior (~1.5-2mm) por bruxismo',
    otros_hallazgos: {
      hallazgo_clave: 'CAL máximo 4.4mm, pero toda la pérdida es lingual (recesión traumática), no proximal/bucal',
      causa_recesion: 'Multifactorial: fenotipo delgado, cepillado horizontal traumático, bruxismo nocturno sin protector, respiración oral nocturna, mordida profunda anterior',
      velocidad_progresion: 'Muy lenta — aproximadamente 0.19mm/año',
      indice_biopelicula: '64% en la zona lingual (higiene deficiente en el área, especialmente sin uso regular de hilo dental)',
      factor_inflamatorio: 'Mínimo — BOP solo 19%; encía relativamente sana pese a la recesión',
    },
    periodontograma_url: null,
    radiografia_panoramica_url: null,
    radiografia_sextante_1_vestibular: null,
    radiografia_sextante_1_palatino: null,
    radiografia_sextante_2_vestibular: null,
    estadio_correcto: 1,
    extension_correcta: 'Localizada',
    grado_correcto: 'A',
    notas_diagnostico:
      'Estadio I: CAL máximo 4.4mm, pero localizado en zona anteroinferior lingual, con un patrón recesionario, no un patrón periodontal generalizado. Localizado (afecta solo la zona anteroinferior lingual). Grado A: 26 años + velocidad de progresión lenta (≈0.19mm/año) + BOP bajo (19%) + sin comorbilidades sistémicas + sin tabaco = baja velocidad de progresión esperada. El problema principal no es periodontitis severa, sino recesión traumática por bruxismo, cepillado agresivo y respiración oral. Tratamiento: corrección de la técnica de cepillado, protector nocturno para el bruxismo, posible injerto gingival a futuro. Este es el verdadero desafío diagnóstico del quiz: el caso puede parecer "grave" por las recesiones visibles, pero es Estadio I, Grado A — hay que reconocer el patrón de pérdida ósea y de CAL (lingual, no proximal) y no confundirlo con periodontitis primaria.',
    dificultad_caso: 'Muy alta',
  },
];
